delete http://localhost:3003/api/blogs/60cf055419678227e0d19b11
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvaXV5dCIsImlkIjoiNjBjZGJiY2FjM2M1NmE4OWMwZGM0MzkxIiwiaWF0IjoxNjI0MTgwMDk2fQ.IdE8Azr4yB5gc2GMufQGjERTahDI7frVLj7Aqhi_u68

# {
#     "title": "Love",
#     "author": "Ortega",
#     "url": "loam.com",
#     "likes": 9
# }